cifsd: pass a pointer to iface name to sock_setsockopt()
transport_tcp.c:422:5: error: implicit declaration of function 'KERNEL_SOCKPTR'
   422 |     KERNEL_SOCKPTR(iface->name),

KERNEL_SOCKPTR has been removed by commit 519a8a6cf91dd ("net: Revert
"net: optimize the sockptr_t for unified kernel/user address spaces"),
pass the raw iface name pointer to sock_setsockopt() instead.

Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>